version: "3.7"
services:
  database:
    image: postgres:14.3
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_DB=postres
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=postres
#      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
  web:
    build: .
    platform: linux/amd64
    command: bash -c "alembic upgrade head && uvicorn anotherdisk.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "80:80"
    restart: always
    environment:
      - POSTGRES_DB=postres
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=postres
      - POSTGRES_HOST=database:5432
    depends_on:
      - database

