"""initial

Revision ID: 3c0dd7b63940
Revises: 
Create Date: 2022-09-16 00:50:35.242001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c0dd7b63940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
                    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('type', postgresql.ENUM('FILE', 'FOLDER', name='systemitemtype'), autoincrement=False,
                              nullable=False),
                    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['items.id'], name='items_parent_id_fkey',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='items_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')

    # ### end Alembic commands ###
